### ISSUE TITLE
junicode F0001 in ss10 not correct in lualatex, ok in xelatex

### ISSUE THREAD

**Issue by kberry** [latex3/luaotfload#244] opened 2023-01-07 02:21 UTC
the MUFI character F0001 (latin small letter a with stroke through terminal) in the Junicode font, specifically JunicodeTwoBeta-Regular.ttf (https://github.com/psb1558/Junicode-font/blob/master/fonts/ttf/JunicodeTwoBeta-Regular.ttf) is typeset correctly with xelatex, but comes out as some other character with lualatex. Example document:
```
\documentclass{article}
\pagestyle{empty}
\usepackage{fontspec}

\newfontfamily{\Junicode}{JunicodeTwoBeta-Regular.ttf}
\newcommand{\sgl}[1]{{\Junicode\addfontfeature{StylisticSet=10}#1}}

\begin{document}
\sgl{ó°\200\201}
\end{document}
```

I'll attach the output with the two engines (the wrong lua output first, then the correct xe). This is with current TL and current Junicode.

If there are questions about how that character is supposed to work, Janusz Bien <jsbien@mimuw.edu.pl> is the one who's using it. It came up in a TUGboat article of his. 

Thanks,
Karl

P.S. I guessed this was in luaotfload, but I guess it could be an engine issue or somewhere else ...

![f1lua](https://user-images.githubusercontent.com/362855/211127233-283eced8-1cdc-4044-863a-d5b83cd4556c.png)
![f1xe](https://user-images.githubusercontent.com/362855/211127234-1087b34d-c3a1-45a6-a8fa-9f8a563d9757.png)

[f0001-lua.pdf](https://github.com/latex3/luaotfload/files/10365318/f0001-lua.pdf)
[f0001-xe.pdf](https://github.com/latex3/luaotfload/files/10365319/f0001-xe.pdf)

**Comment by zauguin** [comment] 2023-01-07 17:15
Duplicate of #185.

The HarfBuzz mode is not affected, for `mode=node` this is by design.

**Closed by zauguin** 2023-01-07 17:15 UTC
Labels: duplicate, wontfix, works with mode=harf

**Comment by zauguin** [comment] 2023-01-07 17:17
Duplicate of #185

**Comment by kberry** [comment] 2023-01-07 23:32
Thanks, it does work for me in harf mode.

I had naively thought that harf mode would be the default in lualatex, since it uses the luahbtex engine. Would that be possible, or is it too much to consider (ever)?

**Comment by zauguin** [comment] 2023-01-08 02:22
Ever is a long time, but I don't see such a change (anytime soon).
These are actually two questions though:

  * The default for luaotfload. Since most LaTeX documents use fontspec which explicitly sets a mode by default this doesn't really affect most LaTeX documents and mostly concerns plain users. There the same document might be compiled with both engines and IMO this shouldn't lead to different results unless the author explicitly requests something which only works in one of them, otherwise it leads to hard to predict behavior.
  * The default for fontspec. Since this would only affect LaTeX documents which always should have HarfBuzz available it would be more doable, but I don't think changing it would make sense. Neither of the modes is strictly superior to the other one and especially for documents written in Latin script `node` mode is often a very good choice. Also quite some users try to patch font features which can't work in HarfBuzz mode. Together with worse linebreaking behavior in HarfBuzz mode  with some fonts it's really not reasonable to change the default. (Changing the default mode based on the font make be useful though since most fonts have one of the modes where they work better, but that can already be done with `.fontspec` files.

(Interesting side remark: The default is changed to HarfBuzz in the `polyglossia` package for some reasons. I'm not convinced that that's the right call, but it definitely helps with debugging...)
