### ISSUE TITLE
copy &paste of roboto font

### ISSUE THREAD

**Issue by u-fischer** [latex3/luaotfload#125] opened 2019-12-09 21:57 UTC
~~~~
\documentclass[a4paper]{scrartcl}
\usepackage{fontspec}
\setmainfont{Roboto}
\usepackage{l3pdf}
\ExplSyntaxOn
\pdf_uncompress:
\ExplSyntaxOff
\begin{document}
This is a test. 
\end{document}
~~~~

## lualatex

When copiled with lualatex  copy& paste in the adobe reader gives:

T h i s i s a t e s t .

The selected area looks like this

![image](https://user-images.githubusercontent.com/4047173/70475700-64387800-1ad5-11ea-8258-54800c5084ef.png)

The pdf page stream shows  kerning between every char:
~~~~
<0038>-625<004C>-577<004D>-254<0057>-1048<004D>
~~~~

and the font is scaled as `/F37 5.3267 Tf`

## xelatex 
copy & paste gives

This is a test.

The selected area looks like this:

![image](https://user-images.githubusercontent.com/4047173/70475938-f0e33600-1ad5-11ea-9188-38784de03218.png)

the page stream has 

`<0038004c004d0057>-247<004d0057>-248<0045>`

and the scaling: `/F1 10.9091 Tf`

It looks as if luaotfload is using a quite different font size. Where does this difference comes from?

**Comment by zauguin** [comment] 2019-12-09 22:43
@u-fischer I'm unable to reproduce this. I get the same values for lualatex as you get for xelatex. Also a  font size of `5.3267` seems odd here. Can you send me the PDF and the log?

**Comment by zauguin** [comment] 2019-12-09 23:32
This is an artifact of how LuaTeX handles font with non-standard upem values. The Roboto font bundled with TeXLive has been converted from TrueType to OpenType without changing `upem` from 2048 to 1000. LuaTeX tries to work around viewer bugs by forcing `upem` to 1000 and fixing the differences by changing the font size and adding kerning. This is detected as spaces by some viewers. There is not much we can do here. LuaTeX could be changed to behave similar to XeTeX, but that would reintroduce  multiple issues with buggy printers.

The best fix would be to avoid such fonts altogether. For example by using the original TTF fonts instead of converting them to OTF (This  actually used to be the case up to 2018 and it is the reason why the problem only occured for some people: If Roboto is installed as system font, the TTF system font is used) or by using a normal upem value of 1000 for the OTF version.

**Comment by krumeich** [comment] 2019-12-10 08:04
@zauguin Thanks for the explanation (and of course thanks to @u-fischer for opening this issue)

Here are the log file and pdf output of the original example that I posted to the TeX Live mailing list:

[test.log](https://github.com/latex3/luaotfload/files/3943626/test.log)
[test.pdf](https://github.com/latex3/luaotfload/files/3943627/test.pdf)

**Comment by zauguin** [comment] 2019-12-17 02:14
Fixed in the Roboto font package

**Closed by zauguin** 2019-12-17 02:14 UTC
