### ISSUE TITLE
cmu serif font: old style numbers don't have correct ToUnicode entries

### ISSUE THREAD

**Issue by u-fischer** [latex3/luaotfload#109] opened 2019-10-26 19:07 UTC
reported https://tug.org/pipermail/luatex/2019-October/007254.html

~~~~
\documentclass{article}
\usepackage{l3pdf}
\ExplSyntaxOn
\pdf_uncompress:
\ExplSyntaxOff
\begin{document}
\font\test={name:CMU Serif:mode=node;script=latn;language=DFLT;+tlig;+onum;}
\test
abc123
\end{document}
~~~~

gives 

~~~~
6 beginbfchar
<0042> <0061>
<0043> <0062>
<0044> <0063>
<0874> <FFFD>
<0875> <FFFD>
<0876> <FFFD>
endbfchar
~~~~

It is font specific, other fonts works. With xelatex copy & paste seems to be ok.

**Comment by zauguin** [comment] 2019-10-27 11:21
The problem is that OpenType onts don't directly contain such tounicode values, they *only* contain the mapping used for input. (There the codepoint for `1` obviously is assigned to the normal `1` etc.), so the fontloader is basically guessing the right mapping based on their names. This works fine for fonts like Latin Modern where oldstyle numbers have names like `eight.oldstyle` because one heuristic is: "Ignore everything after the first dot", but CMU Serif uses e.g. `eightoldstyle`. This name can be mapped by the Adobe Glyph List, but to some codepoint in the private use area, so the fontloader prefers a generic `U+FFFD` (aka REPLACEMENT CHARACTER). I don't see a nice way to auto detect this mapping, so we could add an overwrite. Currently we do not change the overwrite table, so we could either sedt our own overwrites or ask the ConTeXt team to modify the default overwrite table in `font-map.lua`.

**Comment by ndlecic** [comment] 2019-10-27 11:34
> so the fontloader prefers a generic `U+FFFD` (aka REPLACEMENT CHARACTER).
> I don't see a nice way to auto detect this mapping, so we could add an overwrite.

However, 'tounicode' values have been correct prior to luaotfload-3.0, for many years. They became 0xFFFD just in TL2019.

For example, "oneoldstyle":
```
[63281]={
   ["height"]=296222.72,
   ["index"]=2164,
   ["tounicode"]="F731",
   ["unicode"]=63281,
   ["width"]=327680,
  },
```

**Comment by zauguin** [comment] 2019-10-27 12:28
> > so the fontloader prefers a generic `U+FFFD` (aka REPLACEMENT CHARACTER).
> > I don't see a nice way to auto detect this mapping, so we could add an overwrite.
> 
> However, 'tounicode' values have been correct prior to luaotfload-3.0, for many years. They became 0xFFFD just in TL2019.

Actually prior to v2.9. There has been a fontloader change to no longer use tounicode values from the private use area.

Also "correct" pretty much depends on your definition. The old `tounicode` value was 63281, corresponding to U+F731 from the private use area. So officially, this value doesn't have any predefined meaning and the interpretation relied on PDF viewers interpreting this using Adobe's glyph list. On the other hand, such guessing can have unintended consequences for fonts which use the Private Use Area for Private Use. So instead of using Private Use Codepoints and hoping that the PDF viewer reads them in the same way as we intended, it would be nicer to actually set a regular codepoint as tounicode value, which would be e.g. U+0031 (49) for `oneoldstyle` but this requires the overload mentioned above.

**Comment by ndlecic** [comment] 2019-10-27 13:22
> Also "correct" pretty much depends on your definition. The old `tounicode` value was 63281, corresponding to U+F731 from the private use area.

"Correct" in the sense that (1) it was (probably) the best guess according to the font itself, that (2) the values were different, and that (3) copying in plain text from a document usually worked, since oldstyle numerals occur at the same place in many fonts.

>  it would be nicer to actually set a regular codepoint as tounicode value, which would be e.g. U+0031 (49) for `oneoldstyle` 

Anyway, I understand your explanation. You suggest that luatex-generated PDF output should be the same as xetex's? (Old numerals copy from xetex-generated documents as ordinary digits.) 

It also should be noted that not just oldstyle numerals became FFFD in new PDFs, but many other symbols as well; and the problem is the same with the whole CMU family.

For users like me the main problem is backward compatibility. I have a huge heap of CMU documents which should remain exactly the same when compiled with new versions of luatex. Can you think of some reasonable workaround?

**Comment by u-fischer** [comment] 2019-10-27 15:37
@zauguin The obvious idea would be to use glyphtounicode, but it seems to have no effect in luatex. Do you know if is it actually meant to work? 

~~~~
\documentclass{article}
\usepackage{l3pdf}
\ExplSyntaxOn
\pdf_uncompress:
\ExplSyntaxOff
\protected\def\pdfglyphtounicode {\pdfextension glyphtounicode }
\input glyphtounicode.tex

\pdfvariable gentounicode=1

\usepackage{fontspec}
\setmainfont[Numbers=OldStyle]{CMU Serif}

\begin{document}
abc1238
\end{document}
~~~~

**Comment by zauguin** [comment] 2019-10-27 16:58
@u-fischer 
> @zauguin The obvious idea would be to use glyphtounicode, but it seems to have no effect in luatex. Do you know if is it actually meant to work?

No, `glyphtounicode` is only for traditional 8-bit fonts, wide fonts work completely independent. AFAIR are the values set using `pdfglyphtounicode` not available through Lua, so we also can't emulate really this. We could create a overwrite table based on `texglyphlist-g2u.txt`, one relevant source of glyphtounicode.tex, though.

> > it would be nicer to actually set a regular codepoint as tounicode value, which would be e.g. U+0031 (49) for `oneoldstyle`
> 
> Anyway, I understand your explanation. You suggest that luatex-generated PDF output should be the same as xetex's? (Old numerals copy from xetex-generated documents as ordinary digits.)

I think that in this case, XeTeX produces the best behaviour because the choice between lining or old-style numerals normally is a question of font design (or font options), so as plain text they are the same.

> 
> It also should be noted that not just oldstyle numerals became FFFD in new PDFs, but many other symbols as well; and the problem is the same with the whole CMU family.
> 
> For users like me the main problem is backward compatibility. I have a huge heap of CMU documents which should remain exactly the same when compiled with new versions of luatex. Can you think of some reasonable workaround?

AFAICT current versions of the fontloader (the part which we include from ConTeXt) will not create tounicode values from Unicode's Private Use areas. So you either need an old fontloader (they will often require patches to be compatible with current LuaTeX versions and might not work with current luaotfload versions), you have to patch the font after loading it (at this point some information might already be discarded), patch the fontloader to revert to it's old behaviour or ask the ConTeXt team to revert to the old behaviour (maybe as an optional setting).

**Comment by u-fischer** [comment] 2019-10-27 17:13
@zauguin I did sent a question to the context list. Let's wait what happens. But in general it would be good to have a method to map such chars to some unicode: it is a requirement of pdf/UA that everything has a tounicode mapping, and it could be that <FFFD> is not allowed.

**Comment by khaledhosny** [comment] 2019-10-29 00:24
The `harf` mode code has some rather convoluted logic to handle this, since the PDF glyph to Unicode notion is not compatible with OpenType character <-> glyph relationships.

* The logic needs to be applied after shaping and can only be applied to characters/glyphs actually used not everything in the font. This because OpenType can have complex, context and script/language-sensitive rules and “static” analysis of them is unpractical (unless one takes short-cuts, which will make them unreliable).
* If, after shaping, there is a unique mapping to one or more sequence of characters for any given glyph, add said mapping to ToUnicode mapping of the font,
* otherwise use ActualText spans (and try to make them as minimum as poosiple, since PDF readers can’t select part of such spans and treats it as a single unit).

AFAIK, ConTeXt fontloaders uses the ”static” analysis approach (may be in addition to some heuristic using glyph names, I don’t recall for sure). I don’t know if it is possible for luaotfload to post-process the fontloader output and do something as outlined above (probably not as I don’t think the fontloader maintains glyph to character mapping after processing).

**Comment by zauguin** [comment] 2019-10-31 00:13
Should be fixed in bc7268f5502f00f3c2023d996a883fcca6ad8234.
@u-fischer Could you test this?

**Comment by u-fischer** [comment] 2019-10-31 08:35
@zauguin yes, will do. But currently I'm confused about the state of the branches. You seem to have added the missing fonts for the docu, but where are they?

**Comment by zauguin** [comment] 2019-10-31 11:07
> @zauguin yes, will do. But currently I'm confused about the state of the branches. You seem to have added the missing fonts for the docu, but where are they?

I thought I can just add them, so I tried but Travis still couldn't find them so I retracted that commit. The state of the branches should be as if this never happened.


> @zauguin It seems to work fine. Can one (and if yes how) in a document add or change entries? I would then add this also to the documentation.

Not really. We could add an interface to change this list, but I think the lookup is done at font caching time, so changing would have to be consistent over all documents. We could add an interface to change this for individual fonts using a feature but I don't know if that would be useful.

**Closed** 2019-11-25 21:45 UTC
