### ISSUE TITLE
slot_of_name doesn't return all slots

### ISSUE THREAD

**Issue by schlcht** [latex3/luaotfload#198] opened 2021-08-04 23:28 UTC
The function `aux.slot_of_name` doesn't always return a slot number (therefore also `gid_of_name`, which relies on it). Consider the following:

```
\newif\iflua
\ifx\directlua\undefined\else
\luatrue
\input luaotfload.sty
\fi
\font\x=[NewCM10-Book.otf] \x
\def\test#1{#1:
  \iflua
    \directlua{tex.print(luaotfload.aux.slot_of_name(font.current(),"#1",true))}
  \else
    \the\XeTeXglyphindex"#1"
  \fi \par}
\test{A}
\test{bar}
\test{uni1F88}
\test{uni1F88.alt}
\bye
```

I wonder (a) whether this is expected, and (b) if anything could be done about it? Note that xetex is able to return the GID in all cases.

**Comment by zauguin** [comment] 2021-10-25 23:58
> I see you've fixed this in dev, and it does seem to work for most glyphs, so thanks for that already, however here's something I can't quite explain. The following document works fine with plain luatex, but fails with lualatex on the last two glyphs, returning too large values. There's no problem if not in harf mode.

Regarding plain LuaTeX: Did you run `luatex` or `luahbtex`? With `luatex` HarfBuzz isn't available, so `mode=harf` is more or less ignored and therefore you can't see `harf` behavior.

> 
> Maybe just a coincidence, but some testing seems to indicate that only those glyphs fail that are defined in the font after the `.notdef` glyph (which itself also fails).

Technically *all* glyphs are after the `.notdef` glyph in a font file (The `.notdef` glyph is not identified by name but as the first glyph in the font.

That aside, the issue is about unencoded glyphs (glyph which are not the default for any Unicode codepoint). For them the slot returned by `slot_of_name` isn't their Unicode codepoint (since that doesn't exists), so their slot is a marker higher than the valid Unicode range. This isn't accepted by `\char` which can be worked around. It also leads to glyphs which have to be protected since we currently can only pass Unicode text and not glyphs without encoding to HarfBuzz. (Depending on your usecase this can be a good idea anyway since it ensures that the given glyph is actually used and not replaced by font features.

In the current LaTeX sources you can look [at the definition of `\@remove@tlig@@@`](https://github.com/latex3/latex2e/blob/develop/base/ltoutenc.dtx#L2958-L2976), it is basically `\char` except that it applies the two changes you need here. (Please don't actually use `\@remove@tlig@@@` but create a copy for it if you need it, `\@remove@tlig@@@` might change or get removed in later versions)

> (As a side question: do you already have a release date for the next version? I plan to publish a new `microtype` version soon-ish, which would also contain settings for NewCM, including these named glyphs that at the moment still give warnings/errors.)

Soon-ish... We are only waiting for someone to have the time to document the changes and do a release right now.

**Comment by zauguin** [comment] 2022-03-01 19:14
The original issue is fixed in the latest release, so I'll close this here.

**Closed by zauguin** 2022-03-01 19:14 UTC
Labels: enhancement, works with mode=harf, fixed in dev
